sudo: false
language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
before_install:
  - npm install -g npm
  - npm install -g cordova
  - npm install -g grunt-cli
before_script:
  - npm install
script:
  - grunt precommit